OMNA/dm/dm_ac_registry.html
To resolve:
https://helpdesk.openmobilealliance.org/browse/OPEN-7913
https://helpdesk.openmobilealliance.org/browse/OPEN-7918
=> Update DM AC Registry for GSMA TSGVVEC group

OMNA/LwM2M/reserved.xml
Change AVSystem to AVSystem sp. z o.o.
=> Update AVSystem company name

OMNA/LwM2M/LwM2MRegistry.html, package-lock.json
Reverts OpenMobileAlliance/technical.openmobilealliance.org#109
=> Revert "[ADMIN] Update lwm2m registry based on David Navarro email"

OMNA/LwM2M/LwM2MRegistry.html
=> Update lwm2m registry based on David Navarro table.

OMNA/LwM2M/LwM2MRegistry.html
A note for objects reservation is deleted.
=> remove note for objects reservation

OMNA/LwM2M/reserved.xml
A new entry for 50 objects reservation has been added, based on the request of Kim Chew (Landis+Gyr), see https://helpdesk.openmobilealliance.org/browse/OPEN-7966.
=> landis+gyr objects reservation entry

OMNA/LwM2M/reserved.xml
A new entry for 50 objects reservation has been added, based on the request of Diachok Viacheslav (Sinai RnD), see https://helpdesk.openmobilealliance.org/browse/OPEN-7970 and related https://helpdesk.openmobilealliance.org/browse/OPEN-7969.
=> sinai rnd objects reservation entry

index.html
Update the dynamic table with explanatory text
=> update index with explanation text

OMNA/LwM2M/reserved.xml
A new bulk reservation of 50 objects has been added, based on the request of Seongyun Kim (Korea Electronics Technology Institute), see https://helpdesk.openmobilealliance.org/browse/OPEN-7995.
=> Korea El Tech Inst bulk reservation objects entry

OMNA/LwM2M/reserved.xml
A new bulk reservation of 50 objects has been added, based on the request of Ludwig Linder (M2M Solution AB), see https://helpdesk.openmobilealliance.org/browse/OPEN-8002.
=> [ADMIN] M2M Solution AB reservation entry

OMNA/LwM2M/reserved.xml
A new bulk reservation of 50 objects has been added, based on the request of Mariusz Czeremcha (PGE Dystrybucja S.A.), see https://helpdesk.openmobilealliance.org/browse/OPEN-8010
=> [ADMIN] PGE Dystrybucja bulk reservation objects entry

OMNA/LwM2M/reserved.xml, index.html
New PR against gh-pages to merge this approved content #145
=> Publish  PGE Dystrybucja bulk reservation

OMNA/LwM2M/reserved.xml
A new bulk reservation of 50 objects has been added based on the request of Alexis Maurin (BH Technologies), see https://helpdesk.openmobilealliance.org/browse/OPEN-8013.
=> [ADMIN] BH Technologies bulk reservation objects entry

CSS/Site.css, OMNA/LwM2M/LwM2MRegistry-old.html, OMNA/LwM2M/LwM2MRegistry.html, OMNA/LwM2M/_OMNAInformation.html, OMNA/LwM2M/_ObjectIDClasses.html, OMNA/LwM2M/_ResourceIDClasses.html, Scripts/getRepositoryInfo.js, Scripts/lwm2mregistry-tables.js, index.html
This PR introduces two dynamic tables: one for objects and the other for the resources.
Also, simplifies the view of objects, resources, and bulk objects.
The PR is pending DMSO and Utilities review.
=> [ADMIN] Add dynamic tables to the lwm2m registry for objects and resources

OMNA/LwM2M/reserved.xml
A new bulk reservation of 50 objects has been added based on the request of Jonas Blick (Air Quality Measurement), see https://helpdesk.openmobilealliance.org/browse/OPEN-8018.
=> [ADMIN] bulk reservation for Air Quality Measurement

OMNA/LwM2M/LwM2MRegistry.html, OMNA/LwM2M/reserved.xml
@jpradocueva,
Please review before merging.
=> update company reservation and fix column name in LwM2M object table

OMNA/LwM2M/LwM2MRegistry.html
=> fix: DDFLink set to zero

OMNA/LwM2M/LwM2MRegistry.html, OMNA/LwM2M/reserved.xml
Merge content for https://github.com/OpenMobileAlliance/technical.openmobilealliance.org/pull/165
=> [ADMIN] Re-introduce functionality of inactive for TSLinks and DDFLinks when set to 0

OMNA/LwM2M/reserved.xml
A new bulk reservation of 50 objects has been added based on the request of Jonas Blick (CaraTech AB), see https://helpdesk.openmobilealliance.org/browse/OPEN-8027.
=> [ADMIN] bulk reservation for CaraTech AB

OMNA/LwM2M/reserved.xml
Updated company name to vonRoll hydro.
=> update company name

publications.json
Updated description as it is in the Introduction section of the original document.
=> [ADMIN] Update publications.json

publications.json
@gocadimic, I have added one of the Utilities whitepaper to the `publications.json` file.
Please add the other whitepaper, [OMA-WP-LwM2M-Metering-Use-Case-20231001-A.pdf](https://openmobilealliance.org/documents/whitepapers/OMA-WP-LwM2M-for-Utilities/OMA-WP-LwM2M-Metering-Use-Case-20231001-A.pdf) following this example.
Thanks
=> Add utilities benefits whitepaper

OMNA/LwM2M/reserved.xml
A new bulk reservation of 50 objects has been added based on the request of Roudy Dagher (Sensile Technologies SA), see https://helpdesk.openmobilealliance.org/browse/OPEN-8040.
=> [ADMIN] bulk objects reservation for Sensile Techn

publications.json
Uodated the WP file name [OMA-WP-LwM2M-Metering-Use-Case-20231001-A](https://www.openmobilealliance.org/documents/whitepapers/OMA-WP-LwM2M-for-Utilities/OMA-WP-LwM2M-Metering-Use-Case-20231001-A.pdf)
=> [Admin} Update publications.json

OMNA/LwM2M/reserved.xml
Updated company name in previous bulk reservation range 35400-35449.
=> [ADMIN] Bulk reservation objects for Watts A/S

OMNA/LwM2M/reserved.xml
A new bulk object reservation is available for 35500 to 35549 for Lactec, as requested per https://helpdesk.openmobilealliance.org/browse/OPEN-8075.
=> [ADMIN] Bulk object reservation 35500 to 35549 for Lactec

OMNA/LwM2M/reserved.xml
A new bulk object reservation is available for 35550 to 35599 for Tecsys do Brasil, as requested per https://helpdesk.openmobilealliance.org/browse/OPEN-8079.
=> [ADMIN] Bulk object reservation 35550-35599 for Tecsys

OMNA/LwM2M/reserved.xml
A new bulk object reservation for T-Mobile is available for 35650 to 35699, as requested per https://helpdesk.openmobilealliance.org/browse/OPEN-8085.
=> [ADMIN] Bulk reservation objects 35650-35699 for T-Mobile

OMNA/LwM2M/reserved.xml
A new bulk object reservation for Moxa Inc. is available for 35700 to 35749, as requested per https://helpdesk.openmobilealliance.org/browse/OPEN-8102.
=> [ADMIN] bulk reservation objects 35700-35749 for Moxa Inc

OMNA/LwM2M/reserved.xml
A new bulk object reservation for Autosen is available for 35800-35849, as requested per in the I[ssue#778](https://github.com/OpenMobileAlliance/lwm2m-registry/issues/778)
=> [ADMIN] bulk reservation objects 35800-35849 range for Autosen

OMNA/LwM2M/reserved.xml
A new bulk object reservation for Paradox Engineering SA is available for 35850-35999, as requested per [Helpdesk Issue-8109](https://helpdesk.openmobilealliance.org/browse/OPEN-8109)).
=> [ADMIN] bulk reservation objects 35850-35899 range for Paradox Engineering

public_documents.html
Broken/missing links were added to the whitepaper table.
=> [ADMIN] Update public_documents.html

OMNA/LwM2M/reserved.xml
A new bulk object reservation for Remoticom is available for 35900-35949, as requested per the [helpdesk-issue-8112](https://helpdesk.openmobilealliance.org/browse/OPEN-8112).
=> [ADMIN] bulk reservation objects 35900-35949 range for Remoticom

OMNA/LwM2M/reserved.xml
A new bulk object reservation for Utonomy is available for 35950-35999, as requested per [Helpdesk Issue-8115](https://helpdesk.openmobilealliance.org/browse/OPEN-8115)).
=> [ADMIN] bulk reservation objects 35950-35999 range for Utonomy

OMNA/LwM2M/reserved.xml
A new bulk object reservation for IOX GmbH is available for 36000-36049, as requested per [Helpdesk Issue-8132](https://helpdesk.openmobilealliance.org/browse/OPEN-8132).
=> [ADMIN] bulk reservation range 36000-36049 for IOX GmbH
